# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 00:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.UUIDField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('creation_mode', models.CharField(choices=[('L', 'login'), ('S', 'session')], default='S', max_length=1)),
            ],
            options={
                'db_table': 'carthere',
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('unique_id', models.UUIDField(blank=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(default=None, max_length=30)),
                ('mobile_number', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'inputdata',
            },
        ),
        migrations.CreateModel(
            name='Linkaddress',
            fields=[
                ('unique_id', models.UUIDField(blank=True, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkaddress',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copyloftapp.InputData', verbose_name='Type of check-in'),
        ),
    ]
