# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyloftapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='creation_mode',
            field=models.CharField(choices=[('L', 'login'), ('S', 'session')], default='S', max_length=2),
        ),
    ]
